
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: webhook
webhooks:
- clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZEekNDQXZlZ0F3SUJBZ0lDQitRd0RRWUpLb1pJaHZjTkFRRUxCUUF3R1RFWE1CVUdBMVVFQ2hNT2FYTjAKYVc4dGIzQmxjbUYwYjNJd0hoY05NakF3T1RFMU1qSTBNekkyV2hjTk1qRXdPVEUxTWpJME16STJXakFaTVJjdwpGUVlEVlFRS0V3NXBjM1JwYnkxdmNHVnlZWFJ2Y2pDQ0FpSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnSVBBRENDCkFnb0NnZ0lCQUxpbDJiMFlvTkF5QjEvOHFsWm1iR0h4dVgyRCtSMFZBZ28rbjNVckxvbzVVUE90Qm0zcG93SlgKTi9oRklSL2Y5TXBYNmVhVG9XVGJtZWo1NHVvL2tTUG1zQVJoSnkxakttMGZmNWJwdXdUKzZLK0VYaTZoN0lzTwpiaGZSc2w1YTYxM0ZMR1dpREV1THZqU0dRRXNwZzVsd1dzS3U5SHRjN3ZVYlM1SnZ2TmYrUi9CTWpLaTgremhLCjVJZkRpNy96RlplU1hES0VjeElWMzF5L29hZmdwTmN6cFo3NEkybXMvMVhYblBFcExqT2dOSGV4T2x1THFqYysKeDZTUyt2bXNYaHpDbXErd2JXK0dEWkZSaDV1WEZDcGJCZERWcjNGbXkveDI4S1djc2l1bEd6VVpsWE9lZllwUwpVSlI2Nm9WOVFXSTcrQ1hiQ0hLOVFPUVNGTFExNmVnTk00YTFjZGJ2cVlmZ1hYcXQ5NzNEa2Z4clhoUngrTUhRCmxMdEJ3MDlnTEhmYmhqeGF0VjdpQXlRR1g2c3RKcDNHU2JTTDkzRTZSQnBTRjA3Q0ZhLzNtdEZRS1g0NlFnSE8KRG5tY1ZubFZyZE4zdDZ0NWZmOTd4ZXZYRWNnMnQ4T1p2bHB1bFpGSjl4eFB6cml3VnRWQnhhdDM2R3hXamtBVwphZjY3TUJJUjBCa2ZTcVdlZGpGbjJ3YW96ODdIK21teHpRQTkrV3Q2ZXFhRHpPNExBcFYwOGovZS9PcHpBa3lVClFienNCRVliTHJOcnhJbVJvclhBOXFXSTROWHpSc3ZSa2tNd2ZnVUtNS3pQUFpSakt6bWhRVUxaVWhLYVN2ZVcKYjczMGlGZE9uNzU4bWJrMXFQREhJSlhiazE3Q0VQdVJXZ1BpMXByRFlLeUI2bVRscDNBREFnTUJBQUdqWVRCZgpNQTRHQTFVZER3RUIvd1FFQXdJQ2hEQWRCZ05WSFNVRUZqQVVCZ2dyQmdFRkJRY0RBZ1lJS3dZQkJRVUhBd0V3CkR3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVWNWSWNrZ1dDTFlhK2owYVNZdndVZTF2aFFva3cKRFFZSktvWklodmNOQVFFTEJRQURnZ0lCQUpkZE5hNmxkQXE1VkM2cFBiRlBMTjJIUCsrKzFTWU9VZmRCUGpjSworM2UyVXZnektoUmg1akl1VHRaWmZiZ3kvY3Y5YTlPWkZ5eHJIai9tQWZ6UFlzUnBCVHloWkpGdEtKZ3NEUUVDClFlbVo1VG9wTVhKeXZjZzVsb2M1N2pnbDdDOUFScHBna1dDYWxoNEc1M1hXZGNyZ3YxMmphN2taSnlqMlNWVlkKVUlsY3FEUlplaFVvbDFLdUsrdmZxTjFVT05VUnZ2emlpQ2VSbGpJVko3YThhL1l4Mkh4ME9KQkRGakdRTUJtSQoxeTBVZGZvbEZKVjhFTXhIK2Z0dUpFTi9XaGdhTWpuNTZHUlNmUXdEL21NcmNGSzJGN1B3T21WamtHY3dTNDJnCk13TldMQ2VLV1JNWEFMZVZFYzFVS3NuU1UvbmJ0dnhIKytvejR4U2ZHVEVmazgya3ZsQU9ocnpyTDJ3ZmVyV00KMlF2anphdlovSGJmVWZFWUxuOEFRZEU4UWdCUktXOFFlendKWTZWdjJzVmpnelhiZGxwNUgyZWRST0xiTHpxWQpOY3BQQXdWUlowRDhwUkhoUnVXY0U5Z3hzMnY5Zy8vUE1DU2lkVXkyb3gwYTJWalZackRoVXlxR1J6QkszOXd0CjcwWTVtUnB0S252dFc1T3VUdWNqRG43QlF1TjF1ZFg4ZXlCdXR2M2JoM1IrZlhBRUN6b2VYUzk3ZWJuMmYyUjcKdXYyRUxSWmVyYmNyVnFsRDRCTEpLdk1WQ2x5ODJTeE12azdJK1ppYUtrUXRpdE52eW5nNUpvZXpXMkx4emJpMgpBdHBxd21wT0lQQWZTY003VGJNWlNFTWRPNnY4cHpTUUZ2Tno4UEVIRFIvbTNybHI4Z3ZXcEFGTlpvZU5DaVp2ClNCUVgKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    service:
      name: istio-operator-controller-manager-service
      namespace: istio-system
      path: /validate-istio-config
  failurePolicy: Fail
  matchPolicy: Exact
  name: istio.validation.banzaicloud.io
  rules:
  - apiGroups:
    - istio.banzaicloud.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    resources:
    - istios
    scope: '*'
  sideEffects: Unknown
  timeoutSeconds: 30
